import pool from '../../database/connection.js';

// @desc    Create a new menu category
// @route   POST /api/v1/menu-categories
// @access  Private (Manager/Admin)
const createMenuCategory = async (req, res) => {
    const { restaurant_id, name, display_order  } = req.body;
    // Use `req.file.filename` which is the name generated by multer, not `req.file.name`
    const image_url = req.file ? req.file.filename : null;

    if (!restaurant_id || !name) {
        return res.status(400).json({ message: 'restaurant_id and name are required fields.' });
    }

    try {
        const { rows } = await pool.query(
            'INSERT INTO menu_categories (restaurant_id, name, display_order, image_url) VALUES ($1, $2, $3, $4) RETURNING *',
            [restaurant_id, name, display_order || 0, image_url]
        );
        res.status(201).json(rows[0]);
    } catch (error) {
        if (error.code === '23505') { // unique_violation
            return res.status(409).json({ message: `A menu category named "${name}" already exists for this restaurant.` });
        }
        if (error.code === '23503') { // foreign_key_violation
            return res.status(400).json({ message: 'The specified restaurant (restaurant_id) does not exist.' });
        }
        console.error(error);
        res.status(500).json({ message: 'Internal Server Error' });
    }
};

// @desc    Get all menu categories for a restaurant
// @route   GET /api/v1/menu-categories?restaurant_id=<uuid>
// @access  Public/Private
const getAllMenuCategories = async (req, res) => {
    const { restaurant_id } = req.query;

    if (!restaurant_id) {
        return res.status(400).json({ message: 'A restaurant_id query parameter is required.' });
    }

    const { rows } = await pool.query(
        'SELECT * FROM menu_categories WHERE restaurant_id = $1 ORDER BY display_order ASC, name ASC',
        [restaurant_id]
    );
    res.status(200).json(rows);
};

// @desc    Get a single menu category by ID
// @route   GET /api/v1/menu-categories/:id
// @access  Public/Private
const getMenuCategoryById = async (req, res) => {
    const { id } = req.params;
    const { rows } = await pool.query('SELECT * FROM menu_categories WHERE category_id = $1', [id]);

    if (rows.length === 0) {
        return res.status(404).json({ message: 'Menu category not found' });
    }

    res.status(200).json(rows[0]);
};

// @desc    Update a menu category
// @route   PATCH /api/v1/menu-categories/:id
// @access  Private (Manager/Admin)
const updateMenuCategory = async (req, res) => {
    const { id } = req.params;

    const { rows: currentRows } = await pool.query('SELECT * FROM menu_categories WHERE category_id = $1', [id]);
    if (currentRows.length === 0) {
        return res.status(404).json({ message: 'Menu category not found' });
    }

    // Merge existing data with new data from request body for a true PATCH experience
    const updatedData = { ...currentRows[0], ...req.body };

    // If a new file is uploaded, update the image_url.
    // Note: You might want to delete the old image from the filesystem here.
    if (req.file) {
        updatedData.image_url = req.file.filename;
    }
    const { name, display_order, image_url } = updatedData;

    const { rows } = await pool.query(
        'UPDATE menu_categories SET name = $1, display_order = $2, image_url = $3 WHERE category_id = $4 RETURNING *',
        [name, display_order, image_url, id]
    );

    res.status(200).json(rows[0]);
};

// @desc    Delete a menu category
// @route   DELETE /api/v1/menu-categories/:id
// @access  Private (Manager/Admin)
const deleteMenuCategory = async (req, res) => {
    const { id } = req.params;
    const { rowCount } = await pool.query('DELETE FROM menu_categories WHERE category_id = $1', [id]);

    if (rowCount === 0) {
        return res.status(404).json({ message: 'Menu category not found' });
    }

    res.status(204).send();
};

export { createMenuCategory, getAllMenuCategories, getMenuCategoryById, updateMenuCategory, deleteMenuCategory };
